server:
  port: 8082
  
resilience4j:
  retry:
    instances:
      retryApi:
        max-attempts: 3
        wait-duration: 5s
        retry-exceptions:
          - com.pdev.rempms.candidateservice.exception.FeignCustomException

spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${random.value}
    openfeign:
      okhttp:
        enabled: true

  profiles:
    active: dev
  application:
    name: rempms-candidate-service