
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rempms_document
    username: postgres
    password: 123
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  
resilience4j:
  retry:
    instances:
      retryApi:
        max-attempts: 3
        wait-duration: 5s
        retry-exceptions: 
          - com.pdev.rempms.documentservice.exception.FeignCustomException

spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${random.value}
    openfeign:
      okhttp:
        enabled: true
        
  thymeleaf:
    prefix: "file:src/main/resources/template/"

# ========================= locations ==========================
document:
  base:
    file:
      path: C:\document-data\
    font:
      path: "src/main/resources/fonts/TheSansSemiLight Plain.ttf"
  max:
    image: 4000000
    document: 50000000