server:
  port: 9001

resilience4j:
  retry:
    instances:
      retryApi:
        max-attempts: 3
        wait-duration: 5s
        retry-exceptions: #The list of that exception that will trigger a retry
          - com.pdev.user_service.exception.FeignCustomException

spring:
  cloud:
#    consul:
#      host: ${CONSUL_SERVER_ADDRESS:localhost}
#      port: 8500
#      discovery:
#        instanceId: ${spring.application.name}:${random.value}
    openfeign:
      okhttp:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "http://localhost:8070/eureka/"
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

one:
  time:
    password:
      CHAR_POOL: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*+=-_"
      PASSWORD_LENGTH: 8

logging:
  level:
    org:
      springframework:
        cloud: DEBUG