
server:
  port: 7080

##DB properties
spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_SERVER_ADDRESS:localhost}:5432/rempms_candidate
    username: postgres
    password: 123
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

build:
  version: "1.0"

accounts:
  message: "Welcome to EazyBank accounts-related web hooks API with best"
  contactDetails:
    name: "Reine Aishwarya - Product Owners 2025"
    email: "aishwarya@eazybank.com"
  onCallSupport:
    - (453) 392-4858
    - (236) 203-0384