server:
  port: 8081

spring:
  main:
    web-application-type: reactive

  cloud:
    consul:
      host: ${CONSUL_SERVER_ADDRESS:localhost}
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${random.value}
        register: true
        prefer-ip-address: true

    gateway:
      routes:
        - id: iam-service
          uri: lb://iam-service
          predicates:
            - Path=/api/iam/**

        - id: pdev-keycloak-service
          uri: lb://pdev-keycloak-service
          predicates:
            - Path=/api/kcs/**

        - id: rempms-location-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/location/**

        - id: rempms-communication-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/communication/**

        - id: rempms-recruitment-service
          uri: lb://rempms-recruitment-service
          predicates:
            - Path=/api/recruitment/**

        - id: rempms-candidate-service
          uri: http://localhost:7080
          predicates:
            - Path=/api/candidate/**

        - id: rempms-document-service
          uri: lb://rempms-document-service
          predicates:
            - Path=/api/document/**

        - id: rempms-draft-service
          uri: lb://rempms-draft-service
          predicates:
            - Path=/api/draft/**

  openfeign:
    okhttp:
      enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org:
      springframework:
        cloud: DEBUG
