server:
  port: 8081

profiles:
  active: prod

spring:
  application:
    name: rempms-api-gateway-service
    
  main:
    web-application-type: reactive
    
#  cloud:
#    consul:
#      discovery:
#        register: true
#        prefer-ip-address: true
    gateway:
      routes:
        - id: iam-service
          uri: lb://iam-service  
          predicates:
            - Path=/api/iam/**

        - id: pdev-keycloak-service
          uri: lb://pdev-keycloak-service  
          predicates:
            - Path=/api/kcs/**

        - id: rempms-location-service
          uri: lb://rempms-location-service  
          predicates:
            - Path=/api/location/**

        - id: rempms-communication-service
          uri: lb://rempms-communication-service  
          predicates:
            - Path=/api/communication/**

        - id: rempms-recruitment-service
          uri: lb://rempms-recruitment-service  
          predicates:
            - Path=/api/recruitment/**

        - id: rempms-candidate-service
          uri: lb://rempms-candidate-service  
          predicates:
            - Path=/api/candidate/**

        - id: rempms-document-service
          uri: lb://rempms-document-service  
          predicates:
            - Path=/api/document/**

        - id: rempms-draft-service
          uri: lb://rempms-draft-service  
          predicates:
            - Path=/api/draft/**