server:
  port: 7080

resilience4j:
  retry:
    instances:
      retryApi:
        max-attempts: 3
        wait-duration: 5s
        retry-exceptions: #The list of that exception that will trigger a retry
          - com.pdev.rempms.candidateservice.exception.FeignCustomException

spring:
  cloud:
    consul:
      host: ${CONSUL_SERVER_ADDRESS:localhost}
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${random.value}
    openfeign:
      okhttp:
        enabled: true
  config:
    import: "configserver:http://localhost:8071/"

  profiles:
    active: test
  application:
    name: rempms-candidate-service