
spring:
  data:
    mongodb:
      host: ${MONGODB_SERVER_ADDRESS:localhost}
      port: 27017
      database: rempms-draft_management
#      username: mongo
#      password: 123
#      authentication-database: admin

security:
  authorization: "disabled"