
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: rempms-draft
#      username: mongo
#      password: 123
#      authentication-database: admin

security:
  authorization: "disabled"