spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rempms_recruitment
    username: postgres
    password: rempmsprod@123
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none