
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: rempms-draft
#      username: mongo
#      password: 123
#      authentication-database: admin
  
resilience4j:
  retry:
    instances:
      retryApi:
        max-attempts: 3
        wait-duration: 5s
        retry-exceptions:
          - com.pdev.rempms.draftservice.exception.FeignCustomException

spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${random.value}
    openfeign:
      okhttp:
        enabled: true

security:
  authorization: "disabled"